"""Mission geometry preparation and orchestration package."""

from .mission_geometry_core import (
    GeometryCoreError,
    clip_partition_to_safe_area,
    create_safe_area,
    extract_polygon_components,
    prepare_partition_components,
)
from .planning_request import (
    CoveragePlanningRequest,
    LocalPoint2D,
    PlanningRequestError,
)
from .planning_result import (
    CoveragePlanningResult,
    CoverageWaypoint,
    PlanningResultError,
    PlanningServiceRejectedError,
    plan_coverage_response_to_result,
)
from .prepared_component import (
    LocalCartesianFrame,
    PreparedComponent,
    PreparedComponentError,
    make_prepared_components,
)
from .route_record import (
    CoverageRouteRecord,
    GeographicWaypoint,
    ProjectedWaypoint,
    ROUTE_SCHEMA_VERSION,
    RouteRecordError,
    geographic_to_local,
    geographic_to_projected,
    local_to_geographic,
    local_to_projected,
    make_route_records,
    projected_to_geographic,
    projected_to_local,
)
from .start_goal_policy import (
    StartGoalPolicyConfig,
    StartGoalPolicyError,
    StartGoalSelection,
    planning_request_from_anchors,
    select_start_goal,
)
from .sequential_plan_coverage_client import (
    PlanCoverageClientError,
    PlannerRequestTimeoutError,
    PlannerServiceUnavailableError,
    PlannerTransportError,
    RclpyPlanCoverageTransport,
    SequentialClientConfig,
    SequentialPlanCoverageRunner,
    SequentialPlanningError,
)

__all__ = [
    "CoveragePlanningRequest",
    "CoveragePlanningResult",
    "CoverageRouteRecord",
    "CoverageWaypoint",
    "GeographicWaypoint",
    "GeometryCoreError",
    "LocalCartesianFrame",
    "LocalPoint2D",
    "PlanCoverageClientError",
    "PlannerRequestTimeoutError",
    "PlannerServiceUnavailableError",
    "PlannerTransportError",
    "PlanningRequestError",
    "PlanningResultError",
    "PlanningServiceRejectedError",
    "PreparedComponent",
    "PreparedComponentError",
    "ProjectedWaypoint",
    "ROUTE_SCHEMA_VERSION",
    "RclpyPlanCoverageTransport",
    "RouteRecordError",
    "SequentialClientConfig",
    "SequentialPlanCoverageRunner",
    "SequentialPlanningError",
    "StartGoalPolicyConfig",
    "StartGoalPolicyError",
    "StartGoalSelection",
    "clip_partition_to_safe_area",
    "create_safe_area",
    "extract_polygon_components",
    "geographic_to_local",
    "geographic_to_projected",
    "local_to_geographic",
    "local_to_projected",
    "make_prepared_components",
    "make_route_records",
    "plan_coverage_response_to_result",
    "planning_request_from_anchors",
    "prepare_partition_components",
    "projected_to_geographic",
    "projected_to_local",
    "select_start_goal",
]
